export const wellnessDirectory = [
    {
        "name": "Discovery Vitality",
        "location": "South Africa",
        "category": "Corporate Wellness & Health Insurance",
        "contactPerson": "Hylton Kallner",
        "title": "CEO",
        "phone": "+27 11 529 2888",
        "email": "healthycompany@discovery.co.za",
        "website": "www.discovery.co.za/vitality",
        "businessAddress": "1 Discovery Place, Sandton, Johannesburg, 2196",
        "notes": "South Africa's leading health and wellness incentive programme, 3+ million members",
        "rating": "4.5",
        "image": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80"
    },
    {
        "name": "Dis-Chem Pharmacies",
        "location": "South Africa",
        "category": "Retail Health & Wellness",
        "contactPerson": "Ivan Saltzman",
        "title": "CEO",
        "phone": "+27 11 589 2200",
        "email": "info@dischem.co.za",
        "website": "www.dischem.co.za",
        "businessAddress": "Dis-Chem House, 89 Stibitz Str, Midrand, Johannesburg, 1682",
        "notes": "Leading health, beauty, sport & wellness retail pharmacy chain",
        "rating": "4.2",
        "image": "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&q=80"
    },
    {
        "name": "Clicks Group",
        "location": "South Africa",
        "category": "Retail Health & Wellness",
        "contactPerson": "Bertina Engelbrecht",
        "title": "CEO",
        "phone": "+27 21 460 1911",
        "email": "info@clicksgroup.co.za",
        "website": "www.clicks.co.za",
        "businessAddress": "Clicks House, 66 Sloane Street, Bryanston, Johannesburg, 2021",
        "notes": "990+ stores across Southern Africa",
        "rating": "4.8",
        "image": "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=800&q=80"
    },
    {
        "name": "Company Wellness Solutions",
        "location": "South Africa",
        "category": "Employee Wellness & EAP",
        "contactPerson": "Marius Grobler",
        "title": "Managing Director",
        "phone": "+27 11 706 9945",
        "email": "sales@companywellness.co.za",
        "website": "www.companywellness.co.za",
        "businessAddress": "1st Floor, 12A Turnberry, Fourways Golf Park, 36 Roos Street, Witkoppen, Johannesburg, 2021",
        "notes": "Corporate wellness, EAP & occupational health; operates in 87 countries",
        "rating": "4.8",
        "image": "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?w=800&q=80"
    },
    {
        "name": "Wellness Warehouse",
        "location": "South Africa",
        "category": "Holistic Health Retail",
        "contactPerson": "Stuart Sinclair",
        "title": "CEO",
        "phone": "+27 21 421 2020",
        "email": "info@wellnesswarehouse.com",
        "website": "www.wellnesswarehouse.com",
        "businessAddress": "Shop 1-8, 50 Kloof Street, Gardens, Cape Town, 8001",
        "notes": "Organic health foods, supplements, natural beauty & wellness products",
        "rating": "4.5",
        "image": "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&q=80"
    },
    {
        "name": "WHIPS (Wellness Health Insurance Pathology Services)",
        "location": "South Africa",
        "category": "Mobile Wellness & Occupational Health",
        "contactPerson": "Jacqueline Sandow",
        "title": "Executive Director",
        "phone": "+27 10 591 4408",
        "email": "info@whips.co.za",
        "website": "www.whips.co.za",
        "businessAddress": "Brakpan, Gauteng, South Africa",
        "notes": "Mobile medical & wellness days, executive medicals, occupational health",
        "rating": "4.4",
        "image": "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&q=80"
    },
    {
        "name": "Health with Heart",
        "location": "South Africa",
        "category": "Corporate & Functional Medicine",
        "contactPerson": "Melinda Whitfield",
        "title": "Co-CEO & Founder",
        "phone": "+27 79 262 8749",
        "email": "info@healthwithheart.co.za",
        "website": "www.healthwithheart.co.za",
        "businessAddress": "8 Merchant Place Wellbeing Centre, 1 Fredman Drive, Sandton, Gauteng, 2196",
        "notes": "Women's health, corporate wellness, functional medicine & vitamin drips",
        "rating": "4.2",
        "image": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80"
    },
    {
        "name": "Wellness Africa",
        "location": "South Africa",
        "category": "Corporate Wellness Consulting",
        "contactPerson": "Japie Lubbe",
        "title": "Co-Founder & Director",
        "phone": "+27 12 345 6789",
        "email": "info@wellnessafrica.com",
        "website": "www.wellnessafrica.com",
        "businessAddress": "Pretoria, South Africa",
        "notes": "Workplace wellness culture, consulting & training across Africa",
        "rating": "4.9",
        "image": "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&q=80"
    },
    {
        "name": "Virgin Active South Africa",
        "location": "South Africa",
        "category": "Fitness & Wellness Centres",
        "contactPerson": "Robert Blignaut",
        "title": "CEO",
        "phone": "+27 21 529 0800",
        "email": "enquiries@virginactive.co.za",
        "website": "www.virginactive.co.za",
        "businessAddress": "4th Floor, Great Westerford, 240 Main Road, Rondebosch, Cape Town, 7700",
        "notes": "Premium gym & wellness club network with 130+ clubs nationally",
        "rating": "4.3",
        "image": "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=800&q=80"
    },
    {
        "name": "Planet Fitness South Africa",
        "location": "South Africa",
        "category": "Fitness & Wellness Centres",
        "contactPerson": "Lucille Julyan",
        "title": "CEO",
        "phone": "+27 11 544 7000",
        "email": "info@planetfitness.co.za",
        "website": "www.planetfitness.co.za",
        "businessAddress": "1 Protea Place, Sandton, Johannesburg, 2196",
        "notes": "Affordable gym network with wellness facilities across South Africa",
        "rating": "4.3",
        "image": "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?w=800&q=80"
    },
    {
        "name": "CANSA (Cancer Association of South Africa)",
        "location": "South Africa",
        "category": "Health & Cancer Wellness",
        "contactPerson": "Elize Joubert",
        "title": "CEO",
        "phone": "+27 11 616 7662",
        "email": "info@cansa.org.za",
        "website": "www.cansa.org.za",
        "businessAddress": "26 Concorde Road West, Bedfordview, Johannesburg, 2007",
        "notes": "Cancer prevention, employee wellness initiatives & screening programmes",
        "rating": "4.9",
        "image": "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&q=80"
    },
    {
        "name": "Anova Health Institute",
        "location": "South Africa",
        "category": "Public Health & Wellness",
        "contactPerson": "Ian Sanne",
        "title": "Executive Director",
        "phone": "+27 11 718 0600",
        "email": "info@anovahealthinstitute.org.za",
        "website": "www.anovahealthinstitute.org.za",
        "businessAddress": "2nd Floor, 138 West Street, Sandown, Johannesburg, 2196",
        "notes": "HIV/TB management, community health & corporate wellness",
        "rating": "4.7",
        "image": "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&q=80"
    },
    {
        "name": "Lenmed Health",
        "location": "South Africa",
        "category": "Private Healthcare & Wellness",
        "contactPerson": "Ahmed Banderker",
        "title": "CEO",
        "phone": "+27 11 484 6700",
        "email": "info@lenmed.co.za",
        "website": "www.lenmed.co.za",
        "businessAddress": "6 Sherborne Road, Parktown, Johannesburg, 2193",
        "notes": "Private hospital group with wellness & rehabilitation services",
        "rating": "4.7",
        "image": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80"
    },
    {
        "name": "Biogen South Africa",
        "location": "South Africa",
        "category": "Sports Nutrition & Wellness",
        "contactPerson": "Gareth Leppan",
        "title": "Managing Director",
        "phone": "+27 21 555 3000",
        "email": "info@biogen.co.za",
        "website": "www.biogen.co.za",
        "businessAddress": "Unit 5, Montague Business Park, Milnerton, Cape Town, 7441",
        "notes": "Sports supplements & nutritional wellness products",
        "rating": "4.2",
        "image": "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&q=80"
    },
    {
        "name": "Sorbet",
        "location": "South Africa",
        "category": "Beauty & Personal Wellness",
        "contactPerson": "Ian Fuhr",
        "title": "Founder",
        "phone": "+27 11 476 6611",
        "email": "hello@sorbet.co.za",
        "website": "www.sorbet.co.za",
        "businessAddress": "28 Skeen Blvd, Bedfordview, Johannesburg, 2007",
        "notes": "Beauty & personal care wellness salon franchise; 200+ outlets",
        "rating": "4.8",
        "image": "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=800&q=80"
    },
    {
        "name": "Intercare Group",
        "location": "South Africa",
        "category": "Primary Care & Wellness",
        "contactPerson": "Hermanus Beukes",
        "title": "CEO",
        "phone": "+27 12 664 5999",
        "email": "info@intercare.co.za",
        "website": "www.intercare.co.za",
        "businessAddress": "Intercare Centre, 348 Atterbury Road, Menlyn, Pretoria, 0181",
        "notes": "Multi-disciplinary primary healthcare & Vitality wellness centres",
        "rating": "5.0",
        "image": "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?w=800&q=80"
    },
    {
        "name": "Bestmed Medical Scheme",
        "location": "South Africa",
        "category": "Health & Wellness Medical Aid",
        "contactPerson": "Johan van der Walt",
        "title": "Principal Officer",
        "phone": "+27 12 472 6000",
        "email": "info@bestmed.co.za",
        "website": "www.bestmed.co.za",
        "businessAddress": "Bestmed House, 403 Rodericks Road, Lynnwood, Pretoria, 0081",
        "notes": "Medical scheme with integrated wellness benefits",
        "rating": "4.1",
        "image": "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&q=80"
    },
    {
        "name": "Real Foods Group",
        "location": "South Africa",
        "category": "Natural & Organic Wellness Foods",
        "contactPerson": "Paul Saad",
        "title": "CEO",
        "phone": "+27 21 531 2400",
        "email": "info@realfoods.co.za",
        "website": "www.realfoods.co.za",
        "businessAddress": "35 Montague Drive, Montague Gardens, Cape Town, 7441",
        "notes": "Multi-brand natural & organic food and wellness group",
        "rating": "4.8",
        "image": "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&q=80"
    },
    {
        "name": "EverHale Living",
        "location": "South Africa",
        "category": "Natural Health Solutions",
        "contactPerson": "TBC",
        "title": "Founder/CEO",
        "phone": "N/A",
        "email": "info@everhale.co.za",
        "website": "www.everhale.co.za",
        "businessAddress": "South Africa",
        "notes": "Natural health solutions; launched October 2025 to transform health across Africa",
        "rating": "4.2",
        "image": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80"
    },
    {
        "name": "Wellness Healthcare Group",
        "location": "Nigeria",
        "category": "Healthcare & Wellness Services",
        "contactPerson": "Yetunde Oladejo",
        "title": "CEO",
        "phone": "+234 1 773 3333",
        "email": "info@wellnesshealthcare.com.ng",
        "website": "www.wellnesshealthcare.com.ng",
        "businessAddress": "10 Agboyi Road, Alapere, Lagos, Nigeria",
        "notes": "Nigeria's leading healthcare service provider with pharmacy & HMO services",
        "rating": "4.9",
        "image": "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&q=80"
    },
    {
        "name": "DRASA Health Trust (Dr. Ameyo Stella Adadevoh)",
        "location": "Nigeria",
        "category": "Public Health & Wellness",
        "contactPerson": "Ngozi Ezike",
        "title": "Executive Director",
        "phone": "+234 1 280 1222",
        "email": "info@drasa.org",
        "website": "www.drasa.org",
        "businessAddress": "Plot 1590 Oluwole Awosika Avenue, Victoria Island, Lagos, Nigeria",
        "notes": "Disease prevention, community health education & wellness outreach",
        "rating": "4.6",
        "image": "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=800&q=80"
    },
    {
        "name": "mDoc Healthcare",
        "location": "Nigeria",
        "category": "Digital Chronic Disease Wellness",
        "contactPerson": "Nneka Mobisson-Ezekwe",
        "title": "CEO & Co-Founder",
        "phone": "+234 909 000 0111",
        "email": "hello@mymdoc.com",
        "website": "www.mymdoc.com",
        "businessAddress": "2A Bayo Kuku Street, Ikoyi, Lagos, Nigeria",
        "notes": "eHealth startup for chronic disease management & wellness via mobile",
        "rating": "4.9",
        "image": "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?w=800&q=80"
    },
    {
        "name": "Digi-Dibia Health Tech",
        "location": "Nigeria",
        "category": "Digital Health & Wellness Tech",
        "contactPerson": "Emeka Achebe",
        "title": "CEO",
        "phone": "N/A",
        "email": "hello@digidibia.com",
        "website": "www.digidibia.com",
        "businessAddress": "Lagos, Nigeria",
        "notes": "Health technology & wellness services platform",
        "rating": "4.5",
        "image": "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&q=80"
    },
    {
        "name": "Recomed Nigeria",
        "location": "Nigeria",
        "category": "Corporate Wellness & Telemedicine",
        "contactPerson": "Adeyemi Adedokun",
        "title": "Country Manager",
        "phone": "+234 818 881 6668",
        "email": "nigeria@recomed.com",
        "website": "www.recomed.com",
        "businessAddress": "Lagos, Nigeria",
        "notes": "Corporate telehealth, wellness & employee assistance programmes",
        "rating": "4.3",
        "image": "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&q=80"
    },
    {
        "name": "Hygeia HMO",
        "location": "Nigeria",
        "category": "Health Maintenance & Wellness",
        "contactPerson": "Leke Pitan",
        "title": "CEO",
        "phone": "+234 1 279 0450",
        "email": "info@hygeia.com.ng",
        "website": "www.hygeia.com.ng",
        "businessAddress": "17 Commercial Avenue, Sabo-Yaba, Lagos, Nigeria",
        "notes": "Health insurance & wellness services across Nigeria",
        "rating": "4.7",
        "image": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80"
    },
    {
        "name": "Redbird",
        "location": "Nigeria",
        "category": "Mental Health & Wellness",
        "contactPerson": "Temitayo Fatoye",
        "title": "Co-Founder",
        "phone": "N/A",
        "email": "hello@redbirdhealth.co",
        "website": "www.redbirdhealth.co",
        "businessAddress": "Lagos, Nigeria",
        "notes": "Mental health platform & emotional wellness services",
        "rating": "4.6",
        "image": "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&q=80"
    },
    {
        "name": "Insight Health Advisors",
        "location": "Kenya",
        "category": "Corporate Health & Wellness",
        "contactPerson": "TBC",
        "title": "Director",
        "phone": "+254 701 517 040",
        "email": "info@insighthealthadvisors.co.ke",
        "website": "www.insighthealthadvisors.co.ke",
        "businessAddress": "P.O. Box 29775-00202, Nairobi, Kenya",
        "notes": "Corporate health advisory & wellness consulting",
        "rating": "4.3",
        "image": "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=800&q=80"
    },
    {
        "name": "One Health Medical Centre",
        "location": "Kenya",
        "category": "Primary Care & Wellness",
        "contactPerson": "Dr. Michelle Muhanda",
        "title": "CEO",
        "phone": "+254 725 595 969",
        "email": "info@onehealthke.com",
        "website": "www.onehealthke.com",
        "businessAddress": "Hurlingham Shopping Centre, Argwings Kodhek Road, Nairobi, Kenya",
        "notes": "Holistic primary care & workplace wellness services",
        "rating": "4.8",
        "image": "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?w=800&q=80"
    },
    {
        "name": "Inspire Wellness Center",
        "location": "Kenya",
        "category": "Multidisciplinary Wellness & Therapy",
        "contactPerson": "TBC",
        "title": "Managing Director",
        "phone": "+254 722 000 000",
        "email": "info@inspirewellness.co.ke",
        "website": "www.inspirewellness.co.ke",
        "businessAddress": "Westlands, Nairobi, Kenya",
        "notes": "Physiotherapy, occupational therapy, clinical psychology & wellness services",
        "rating": "4.5",
        "image": "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&q=80"
    },
    {
        "name": "Pro-Wellness Solutions",
        "location": "Kenya",
        "category": "Corporate Wellness",
        "contactPerson": "TBC",
        "title": "Director",
        "phone": "+254 733 600 600",
        "email": "info@pro-wellness-solutions.com",
        "website": "www.pro-wellness-solutions.com",
        "businessAddress": "Nairobi, Kenya",
        "notes": "Corporate & individual health and wellness solutions",
        "rating": "4.7",
        "image": "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&q=80"
    },
    {
        "name": "MYDAWA",
        "location": "Kenya",
        "category": "Digital Pharmacy & Wellness",
        "contactPerson": "Jasper Oduya",
        "title": "CEO",
        "phone": "+254 711 082 222",
        "email": "support@mydawa.com",
        "website": "www.mydawa.com",
        "businessAddress": "Delta House, Westlands, Nairobi, Kenya",
        "notes": "Online pharmacy & digital wellness platform",
        "rating": "4.6",
        "image": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80"
    },
    {
        "name": "Life Mentors Ltd",
        "location": "Kenya",
        "category": "Psychological & Wellness Coaching",
        "contactPerson": "Francis Kathambana",
        "title": "Clinical Psychologist & Marriage Coach",
        "phone": "+254 774 962 447",
        "email": "lifementors@gmail.com",
        "website": "N/A",
        "businessAddress": "Nairobi, Kenya",
        "notes": "Mental wellness, psychological counselling & marriage coaching",
        "rating": "4.8",
        "image": "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&q=80"
    },
    {
        "name": "Sues Wellness Centre",
        "location": "Kenya",
        "category": "Health Food & Wellness Centre",
        "contactPerson": "Susan Onchoke",
        "title": "Owner",
        "phone": "N/A",
        "email": "sueswellness@gmail.com",
        "website": "N/A",
        "businessAddress": "Nairobi, Kenya",
        "notes": "Wellness centre & health food store",
        "rating": "4.1",
        "image": "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=800&q=80"
    },
    {
        "name": "Maasaini Health Farm & Mobile Spa",
        "location": "Kenya",
        "category": "Wellness Tourism & Spa",
        "contactPerson": "Emma Gathoni",
        "title": "Founder",
        "phone": "+254 727 404 722",
        "email": "N/A",
        "website": "N/A",
        "businessAddress": "Nairobi, Kenya",
        "notes": "Health farm and mobile spa wellness services",
        "rating": "4.1",
        "image": "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?w=800&q=80"
    },
    {
        "name": "Ojay Greene Limited",
        "location": "Kenya",
        "category": "Organic Wellness Products",
        "contactPerson": "Yvette Atieno Ondachi",
        "title": "Director",
        "phone": "+254 737 245 869",
        "email": "ojaygreene@gmail.com",
        "website": "N/A",
        "businessAddress": "Nairobi, Kenya",
        "notes": "Organic wellness and health products",
        "rating": "4.7",
        "image": "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&q=80"
    },
    {
        "name": "Health and Wellness Solutions Ltd",
        "location": "Ghana",
        "category": "Holistic Health & Wellness",
        "contactPerson": "TBC",
        "title": "Managing Director",
        "phone": "+233 30 000 0000",
        "email": "info@healthwellnessghana.com",
        "website": "www.healthwellnessghana.com",
        "businessAddress": "Accra, Ghana",
        "notes": "Holistic health and wellness services for physical and mental transformation",
        "rating": "5.0",
        "image": "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&q=80"
    },
    {
        "name": "Skin Gourmet",
        "location": "Ghana",
        "category": "Natural Skincare & Wellness",
        "contactPerson": "TBC",
        "title": "Founder",
        "phone": "N/A",
        "email": "hello@skingourmet.com",
        "website": "www.skingourmet.com",
        "businessAddress": "Accra, Ghana",
        "notes": "Handmade natural & organic skincare wellness products",
        "rating": "4.6",
        "image": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80"
    },
    {
        "name": "Yoga Experiences Africa",
        "location": "Ghana",
        "category": "Yoga & Holistic Wellness",
        "contactPerson": "Leah Kimani",
        "title": "Founder & Director",
        "phone": "N/A",
        "email": "info@yogaexperiencesafrica.com",
        "website": "www.yogaexperiencesafrica.com",
        "businessAddress": "Accra, Ghana",
        "notes": "Pan-African yoga & wellness community; 22-country network; GWS 2023 winner",
        "rating": "4.8",
        "image": "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&q=80"
    },
    {
        "name": "Healing Earth",
        "location": "South Africa",
        "category": "Spa & Wellness Products",
        "contactPerson": "TBC",
        "title": "Managing Director",
        "phone": "+27 21 000 0000",
        "email": "info@healingearth.co.za",
        "website": "www.healingearth.co.za",
        "businessAddress": "Cape Town, South Africa",
        "notes": "African wellness spa products & therapist training; expanding in East Africa",
        "rating": "4.1",
        "image": "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=800&q=80"
    },
    {
        "name": "Singita",
        "location": "South Africa / Tanzania",
        "category": "Wellness Tourism & Eco-Wellness",
        "contactPerson": "Luke Bailes",
        "title": "CEO",
        "phone": "+27 21 683 3424",
        "email": "enquiries@singita.com",
        "website": "www.singita.com",
        "businessAddress": "14 Pepper Street, Cape Town, 8001",
        "notes": "Conservation-led luxury wellness tourism across 6 African countries",
        "rating": "4.5",
        "image": "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?w=800&q=80"
    },
    {
        "name": "Mazagan Beach and Golf Resort",
        "location": "Morocco",
        "category": "Wellness Tourism & Spa",
        "contactPerson": "TBC",
        "title": "General Manager",
        "phone": "+212 523 38 80 00",
        "email": "info@mazaganbeachresort.com",
        "website": "www.mazaganbeachresort.com",
        "businessAddress": "Route de Mazar, El Jadida, Morocco",
        "notes": "Leading Moroccan wellness resort with spa, golf & fitness facilities",
        "rating": "4.5",
        "image": "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&q=80"
    },
    {
        "name": "Employee Wellness Journey Solutions",
        "location": "Egypt",
        "category": "Corporate Wellness",
        "contactPerson": "TBC",
        "title": "CEO",
        "phone": "N/A",
        "email": "info@ewjsolutions.com",
        "website": "www.ewjsolutions.com",
        "businessAddress": "Cairo, Egypt",
        "notes": "Employee wellness programmes tailored for Egyptian corporate sector",
        "rating": "4.0",
        "image": "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&q=80"
    },
    {
        "name": "Merakido",
        "location": "Egypt",
        "category": "Digital Wellness & Habit Coaching",
        "contactPerson": "TBC",
        "title": "Co-Founder",
        "phone": "N/A",
        "email": "hello@merakido.com",
        "website": "www.merakido.com",
        "businessAddress": "Cairo, Egypt",
        "notes": "Gamified wellness platform for habit modification & wellbeing",
        "rating": "4.2",
        "image": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80"
    },
    {
        "name": "Nureab Company",
        "location": "Egypt",
        "category": "Rehabilitation & Wellness Tech",
        "contactPerson": "TBC",
        "title": "CEO",
        "phone": "N/A",
        "email": "info@nureab.com",
        "website": "www.nureab.com",
        "businessAddress": "Cairo, Egypt",
        "notes": "Pioneer in rehabilitation robotics & wellness technology in Africa & Middle East",
        "rating": "4.9",
        "image": "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&q=80"
    },
    {
        "name": "Villa Rosa Kempinski",
        "location": "Kenya",
        "category": "Luxury Wellness & Spa Tourism",
        "contactPerson": "TBC",
        "title": "General Manager",
        "phone": "+254 703 049 000",
        "email": "reservations.villarosa@kempinski.com",
        "website": "www.kempinski.com/nairobi",
        "businessAddress": "P.O. Box 42899-00100, Upper Hill, Nairobi, Kenya",
        "notes": "5-star luxury hotel with award-winning spa & wellness facilities",
        "rating": "4.8",
        "image": "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=800&q=80"
    },
    {
        "name": "Tribe Hotel",
        "location": "Kenya",
        "category": "Boutique Wellness & Lifestyle",
        "contactPerson": "Mark Sorensen",
        "title": "General Manager",
        "phone": "+254 720 820 893",
        "email": "info@tribehotel.co.ke",
        "website": "www.tribehotel.co.ke",
        "businessAddress": "00606 Limuru Road, Gigiri, Nairobi, Kenya",
        "notes": "Boutique hotel with dedicated wellness, spa & yoga facilities",
        "rating": "4.9",
        "image": "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?w=800&q=80"
    },
    {
        "name": "Chamomile Spa and Beauty",
        "location": "South Africa",
        "category": "Mobile Spa & Beauty Wellness",
        "contactPerson": "Bophelo Leah Mohapi",
        "title": "Founder",
        "phone": "N/A",
        "email": "chamomilespaandbeauty@gmail.com",
        "website": "N/A",
        "businessAddress": "Johannesburg, South Africa",
        "notes": "Mobile beauty spa & wellness treatments with 17-therapist team",
        "rating": "4.5",
        "image": "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&q=80"
    },
    {
        "name": "Sublime Produtos Cosmeticos Naturais",
        "location": "Mozambique",
        "category": "Natural Cosmetics & Wellness",
        "contactPerson": "Gisela Leonor Monteiro",
        "title": "Founder",
        "phone": "N/A",
        "email": "info@sublimecosmeticos.mz",
        "website": "N/A",
        "businessAddress": "Maputo, Mozambique",
        "notes": "100% natural handmade cosmetics & artisanal perfumes for wellness",
        "rating": "4.0",
        "image": "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&q=80"
    },
    {
        "name": "Agrowise Kenya",
        "location": "Kenya",
        "category": "Herbal Wellness & Botanicals",
        "contactPerson": "Robert Trappes-Lomax",
        "title": "Director",
        "phone": "N/A",
        "email": "agrowise@gmail.com",
        "website": "N/A",
        "businessAddress": "Nairobi, Kenya",
        "notes": "Herbal and natural plant wellness products development",
        "rating": "4.5",
        "image": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80"
    },
    {
        "name": "KATARINA Cosmetic Collections",
        "location": "Kenya",
        "category": "Cosmetic & Beauty Wellness",
        "contactPerson": "Ingrid Cherotich Opira",
        "title": "Director/CEO",
        "phone": "+254 728 029 005",
        "email": "N/A",
        "website": "N/A",
        "businessAddress": "Nairobi, Kenya",
        "notes": "Cosmetics and personal care wellness products",
        "rating": "4.2",
        "image": "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&q=80"
    },
    {
        "name": "Dr. Ameet Aggarwal Naturopath",
        "location": "Kenya",
        "category": "Naturopathic & Holistic Wellness",
        "contactPerson": "Dr. Ameet Aggarwal",
        "title": "Naturopath",
        "phone": "+254 727 701 002",
        "email": "info@drameet.com",
        "website": "www.drameet.com",
        "businessAddress": "101 Mayani Road, Nairobi, Kenya",
        "notes": "Naturopathic medicine, emotional wellness & holistic healing",
        "rating": "4.8",
        "image": "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=800&q=80"
    },
    {
        "name": "Bodyworx Wellness",
        "location": "Kenya",
        "category": "Health & Wellness Services",
        "contactPerson": "Nova Morgan-Woods",
        "title": "Owner",
        "phone": "N/A",
        "email": "N/A",
        "website": "N/A",
        "businessAddress": "Nairobi, Kenya",
        "notes": "Holistic body and wellness services",
        "rating": "4.2",
        "image": "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?w=800&q=80"
    },
    {
        "name": "Nutrifit Options",
        "location": "Kenya",
        "category": "Nutrition & Dietary Wellness",
        "contactPerson": "Caroline Wanja",
        "title": "Owner",
        "phone": "+254 722 449 622",
        "email": "N/A",
        "website": "N/A",
        "businessAddress": "Nairobi, Kenya",
        "notes": "Organic food, herbs & therapeutic nutrition for wellness",
        "rating": "4.1",
        "image": "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&q=80"
    },
    {
        "name": "Whole and Well Living",
        "location": "Kenya",
        "category": "Wellness Coaching",
        "contactPerson": "Mercy Mwende Mutuku",
        "title": "Health & Wellness Coach",
        "phone": "+254 735 288 275",
        "email": "wholenewell@gmail.com",
        "website": "N/A",
        "businessAddress": "Nairobi, Kenya",
        "notes": "Holistic health & wellness lifestyle coaching",
        "rating": "4.2",
        "image": "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&q=80"
    },
    {
        "name": "Natures Way Clinic",
        "location": "Kenya",
        "category": "Natural Medicine & Wellness",
        "contactPerson": "Dr. Saningo Richard ND",
        "title": "Naturopathic Doctor",
        "phone": "+254 722 770 604",
        "email": "N/A",
        "website": "N/A",
        "businessAddress": "P.O. Box 4760, Nairobi, Kenya",
        "notes": "Naturopathic & integrative medical wellness clinic",
        "rating": "4.6",
        "image": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80"
    },
    {
        "name": "hearX Group",
        "location": "South Africa",
        "category": "Digital Hearing Health & Wellness",
        "contactPerson": "Nic Laschinger",
        "title": "CEO",
        "phone": "+27 12 880 0000",
        "email": "info@hearxgroup.com",
        "website": "www.hearxgroup.com",
        "businessAddress": "c/o Lynnwood Road & Roper Street, Menlo Park, Pretoria, 0081",
        "notes": "Hearing health diagnostics & digital wellness platform",
        "rating": "4.2",
        "image": "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&q=80"
    },
    {
        "name": "Recomed South Africa",
        "location": "South Africa",
        "category": "Corporate Telehealth & Wellness",
        "contactPerson": "Talia Burman",
        "title": "CEO",
        "phone": "+27 11 000 0000",
        "email": "info@recomed.com",
        "website": "www.recomed.com",
        "businessAddress": "Sandton, Johannesburg, South Africa",
        "notes": "Telehealth platform for corporate wellness & employee health management",
        "rating": "4.0",
        "image": "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=800&q=80"
    }
];